version: '3'
services:

  db:
    image: postgres:latest
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: personal-journal
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  server:
    build:
      dockerfile: server/Dockerfile
    container_name: server
    image: personal-journal
    ports:
      - "8081:8081"
    depends_on:
      - db

  client:
    image: node:alpine
    container_name: client
    entrypoint: /bin/sh
    command: -c "npm i && npm run dev"
    ports:
      - "8080:8080"
    working_dir: /srv/app
    volumes:
      - type: bind
        source: ./client
        target: /srv/app
    tty: true
    depends_on:
      - server

volumes:
  postgres_data: