version: '3'

services:
  db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: personal-journal
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      dockerfile: server/Dockerfile
    container_name: spring-boot-app
    ports:
      - "8081:8081"
    depends_on:
      - db

volumes:
  postgres_data: